// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'html',
      value: '<div style="display: flex; align-items: center; padding: 0.5rem; margin: 0.25rem 0; border-radius: 4px; transition: background-color 0.2s;"><img src="/scripts-organizer/img/icons/subscriptions_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg" style="width: 20px; height: 20px; margin-right: 0.5rem;" /><a href="https://www.youtube.com/@DPlugins" target="_blank" rel="noopener noreferrer" style="text-decoration: none; color: var(--ifm-color-emphasis-700); font-size: 0.9rem;">YouTube Channel</a></div>',
    },
    {
      type: 'html',
      value: '<div style="display: flex; align-items: center; padding: 0.5rem; margin: 0.25rem 0; border-radius: 4px; transition: background-color 0.2s;"><img src="/scripts-organizer/img/icons/groups_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg" style="width: 20px; height: 20px; margin-right: 0.5rem;" /><a href="https://www.facebook.com/groups/dplugins" target="_blank" rel="noopener noreferrer" style="text-decoration: none; color: var(--ifm-color-emphasis-700); font-size: 0.9rem;">Facebook Group</a></div>',
    },
    {
      type: 'html',
      value: '<div style="display: flex; align-items: center; padding: 0.5rem; margin: 0.25rem 0; border-radius: 4px; transition: background-color 0.2s;"><img src="/scripts-organizer/img/icons/support_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg" style="width: 20px; height: 20px; margin-right: 0.5rem;" /><a href="https://support.dplugins.com/" target="_blank" rel="noopener noreferrer" style="text-decoration: none; color: var(--ifm-color-emphasis-700); font-size: 0.9rem;">Support Center</a></div>',
    },
    {
      type: 'html',
      value: '<div style="margin: 2rem 0;" /></div>',
    },
    // Auto-generated content below
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebars;
