name: Deploy Scripts Organizer

on:
  push:
    branches:
      - main
    paths:
      - 'plain-classes-gutenberg/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: plain-classes-gutenberg/package-lock.json
      
      - name: Install dependencies
        run: cd plain-classes-gutenberg && npm ci
      
      - name: Build
        run: |
          cd plain-classes-gutenberg
          npm run build
          ls -la build/
          echo "Build completed successfully"
      
      - name: Verify build
        run: |
          cd plain-classes-gutenberg
          echo "Checking build contents:"
          find build/ -type f -name "*.html" | head -10
          echo "Build verification completed"
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./plain-classes-gutenberg/build
          destination_dir: plain-classes-gutenberg 