name: Deploy Root Content

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'README.md'
      - '.github/workflows/deploy-root.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: .
          force_orphan: false
          cname: testdocs.dplugins.com 